# Generated by Django 5.0.6 on 2024-05-19 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(max_length=100)),
                ('question_numbers', models.IntegerField()),
                ('corrects', models.IntegerField()),
                ('category', models.CharField(choices=[('Linux', 'Linux'), ('DevOps', 'DevOps'), ('Code', 'Code'), ('SQL', 'SQL'), ('Random', 'Random'), ('Docker', 'Docker'), ('CMS', 'CMS')], max_length=6)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
