# Generated by Django 5.0.6 on 2024-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='difficulty',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Meduim'), ('Easy', 'Easy'), ('Random', 'Random')], default='Random', max_length=6),
        ),
        migrations.AlterField(
            model_name='exam',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
